[theme]
theme = "gruvbox-dark"
[icons]
icons = "awesome"


[[block]]
block = "pomodoro"
message = "Take a break! For your Arms"
notify_cmd = "notyfy-send 'msg'"

[[block]]
block = "cpu"
info_cpu = 20
warning_cpu = 50
critical_cpu = 90
interval = 1
format = "$barchart $utilization $frequency"

[[block]]
block = "memory"
format = " $icon $mem_total_used_percents.eng(w:2) "
format_alt = " $icon_swap $swap_used_percents.eng(w:2) "

[[block]]
block = "temperature"
format = " $icon $max max "
format_alt = " $icon $min min, $max max, $average avg "
interval = 10
chip = "*-isa-*"

[[block]]
block = "uptime"
interval = 3600 # update every hour

# [[block]]
# block = "xrandr"
# format = " $brightness $resolution "

# # [[block]]
# # block = "custom"
# # command = ''' siemens-on-cn; echo "$([ $? -eq 0 ] && echo SNX || echo OFF)" '''
# # interval = 10

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = " 🍄 $available.eng(w:2) "

[[block]]
block = "disk_space"
path = "/home"
info_type = "available"
alert_unit = "GB"
warning = 20.0
interval = 20
format = "🏠 $available.eng(w:2) "

[[block]]
block = "disk_space"
path = "/data"
info_type = "available"
alert_unit = "GB"
warning = 20.0
interval = 20
format = "💾 $available.eng(w:2)"

[[block]]
block = "weather"
format = "$icon  $weather $temp"
service = { name = "openweathermap", api_key = "e0160e7f77434e10242b1d7bab182e19", city_id = "2867714", units = "metric" }

# [[block]]
# block = "packages"
# package_manager = ["pacman"]
# interval = 600
# format = " $total.eng(w:1) 🙋 "
# format_singular = " $total.eng(w:1) 🙋 "
# critical_updates_regex = "(linux|linux-lts|linux-zen)"
#
[[block]]
block = "speedtest"
interval = 1800
format = "📡 $speed_down.eng(w:4, u:B) $speed_up.eng(w:4,u:B) "


[[block]]
block = "battery"
format = "{$icon |} Bat $percentage {$time |}"
device = "DisplayDevice"
driver = "upower"

[[block]]
block = "notify"
driver = "dunst"
format = " $icon {($notification_count.eng(w:1)) |}"

[[block]]
block = "net"
format = " $icon {$signal_strength $ssid $frequency|Wired connection} via $device "
[[block]]
block = "time"
interval = 5
timezone = "Europe/Berlin"
format = " $timestamp.datetime(f:'%a %d/%m %R') "

