#!/usr/bin/env bash

tmux new-session -s work -n work -d
tmux new-session -s siemens -n siemens -d
tmux new-session -s fun -n fun -d
tmux new-session -s cdm -n cdm -d

tmux select-window -t work:work
tmux send-keys -t work:work "cd ~/Proj/code/industrialedgeperception/IEP && e README.md" Enter
tmux split-window -t work:work -v -l 30%
tmux split-window -t work:work -h -l 30%
tmux send-keys -t fun:fun "curl wttr.in/munich" Enter

tmux select-window -t siemens:siemens
tmux split-window -t siemens:siemens -h -l 30%
tmux send-keys -t siemens:siemens "echo Siemens Stuff" Enter

tmux send-keys -t cdm:cdm "cd ~/Proj/code/cdm-ie/" Enter
tmux send-keys -t cdm:cdm "cmatrix" Enter

tmux select-window -t work:work
tmux -u attach -t work
